### ISSUE TITLE
webrtc-socketio-ios Reason : image not found issue

### ISSUE THREAD

**Issue by nguyentanloc518091** [ankit92ios/iOSRTC-Swift4#1]
dyld: Library not loaded: @rpath/SocketIO.framework/SocketIO
  Referenced from: /var/containers/Bundle/Application/047C34A6-5F4D-4185-85B4-DE1CD45DA8E7/webrtc-socketio-ios.app/webrtc-socketio-ios
  Reason: image not found

**Comment by ankit92ios** [comment]
@nguyentanloc518091  Can you please try this project: https://github.com/ankit92ios/iOSRTC-Swift4/tree/Update_1
Download and run this.
