### ISSUE TITLE
i get error

### ISSUE THREAD

**Issue by nguyentanloc518091** [ankit92ios/iOSRTC-Swift4#3]
when i run on my iphone 5 with this error

i had change to
        

> SocketManager* manager = [[SocketManager alloc] initWithSocketURL:url config:options];
>         self.socket = manager.defaultSocket;

dyld: Symbol not found: __T0BOWV
  Referenced from: /private/var/containers/Bundle/Application/A4A3DE20-5A01-451A-BB63-D383AA8817AB/webrtc-socketio-ios.app/Frameworks/Starscream.framework/Starscream
  Expected in: /private/var/containers/Bundle/Application/A4A3DE20-5A01-451A-BB63-D383AA8817AB/webrtc-socketio-ios.app/Frameworks/libswiftCore.dylib
 in /private/var/containers/Bundle/Application/A4A3DE20-5A01-451A-BB63-D383AA8817AB/webrtc-socketio-ios.app/Frameworks/Starscream.framework/Starscream

**Comment by nguyentanloc518091** [comment]
please help me!!!

**Comment by ankit92ios** [comment]
Please include Starscream.framework by compiling from this link: https://github.com/daltoniam/Starscream
This solution may resolve your problem. I am closing the issue
